services:
  nginx:
    image: nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "${NGINX_LOCAL_PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - PHP_PORT=${PHP_PORT}
  php:
    build:
      context: .
      dockerfile: php/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql
    env_file:
      - ./mysql/mysql.env
    volumes:
      - my-data-volume:/var/lib/mysql
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
volumes:
  my-data-volume:
